component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/rssowl/.*
- ./bin/org/rssowl/core/.*
- ./bin/org/rssowl/core/connection/.*
- ./bin/org/rssowl/core/internal/.*
- ./bin/org/rssowl/core/internal/connection/.*
- ./bin/org/rssowl/core/internal/interpreter/.*
- ./bin/org/rssowl/core/internal/newsaction/.*
- ./bin/org/rssowl/core/internal/persist/.*
- ./bin/org/rssowl/core/internal/persist/dao/.*
- ./bin/org/rssowl/core/internal/persist/migration/.*
- ./bin/org/rssowl/core/internal/persist/pref/.*
- ./bin/org/rssowl/core/internal/persist/search/.*
- ./bin/org/rssowl/core/internal/persist/service/.*
- ./bin/org/rssowl/core/interpreter/.*
- ./bin/org/rssowl/core/persist/.*
- ./bin/org/rssowl/core/persist/dao/.*
- ./bin/org/rssowl/core/persist/event/.*
- ./bin/org/rssowl/core/persist/event/runnable/.*
- ./bin/org/rssowl/core/persist/pref/.*
- ./bin/org/rssowl/core/persist/reference/.*
- ./bin/org/rssowl/core/persist/service/.*
- ./bin/org/rssowl/core/tests/.*
- ./bin/org/rssowl/core/tests/connection/.*
- ./bin/org/rssowl/core/tests/controller/.*
- ./bin/org/rssowl/core/tests/importer/.*
- ./bin/org/rssowl/core/tests/interpreter/.*
- ./bin/org/rssowl/core/tests/model/.*
- ./bin/org/rssowl/core/tests/performance/.*
- ./bin/org/rssowl/core/tests/persist/.*
- ./bin/org/rssowl/core/tests/persist/service/.*
- ./bin/org/rssowl/core/tests/ui/.*
- ./bin/org/rssowl/core/tests/util/.*
- ./bin/org/rssowl/core/util/.*
- ./bin/org/rssowl/ui/.*
- ./bin/org/rssowl/ui/dialogs/.*
- ./bin/org/rssowl/ui/dialogs/properties/.*
- ./bin/org/rssowl/ui/filter/.*
- ./bin/org/rssowl/ui/internal/.*
- ./bin/org/rssowl/ui/internal/actions/.*
- ./bin/org/rssowl/ui/internal/dialogs/.*
- ./bin/org/rssowl/ui/internal/dialogs/bookmark/.*
- ./bin/org/rssowl/ui/internal/dialogs/cleanup/.*
- ./bin/org/rssowl/ui/internal/dialogs/exporter/.*
- ./bin/org/rssowl/ui/internal/dialogs/importer/.*
- ./bin/org/rssowl/ui/internal/dialogs/preferences/.*
- ./bin/org/rssowl/ui/internal/dialogs/properties/.*
- ./bin/org/rssowl/ui/internal/dialogs/welcome/.*
- ./bin/org/rssowl/ui/internal/editors/.*
- ./bin/org/rssowl/ui/internal/editors/browser/.*
- ./bin/org/rssowl/ui/internal/editors/feed/.*
- ./bin/org/rssowl/ui/internal/filter/.*
- ./bin/org/rssowl/ui/internal/handler/.*
- ./bin/org/rssowl/ui/internal/notifier/.*
- ./bin/org/rssowl/ui/internal/search/.*
- ./bin/org/rssowl/ui/internal/services/.*
- ./bin/org/rssowl/ui/internal/undo/.*
- ./bin/org/rssowl/ui/internal/util/.*
- ./bin/org/rssowl/ui/internal/views/.*
- ./bin/org/rssowl/ui/internal/views/explorer/.*
- ./lib/.*
- ./org.rssowl.core/.*
- ./org.rssowl.core/META-INF/.*
- ./org.rssowl.core/schema/.*
- ./org.rssowl.core.tests/.*
- ./org.rssowl.core.tests/META-INF/.*
- ./org.rssowl.core.tests/data/.*
- ./org.rssowl.core.tests/data/importer/.*
- ./org.rssowl.core.tests/data/interpreter/.*
- ./org.rssowl.core.tests/data/performance/.*
- ./org.rssowl.core.tests/data/performance/corpus_10-03-07/.*
- ./org.rssowl.core.tests/data/performance/corpus_10-06-07/.*
- ./org.rssowl.core.tests/data/performance/corpus_10-09-07/.*
- ./org.rssowl.feature/.*
- ./org.rssowl.feature.dependencies/.*
- ./org.rssowl.feature.eclipse/.*
- ./org.rssowl.feature.tests/.*
- ./org.rssowl.lib.db4o/.*
- ./org.rssowl.lib.db4o/META-INF/.*
- ./org.rssowl.lib.db4o/com/.*
- ./org.rssowl.lib.db4o/com/db4o/.*
- ./org.rssowl.lib.db4o/com/db4o/cluster/.*
- ./org.rssowl.lib.db4o/com/db4o/config/.*
- ./org.rssowl.lib.db4o/com/db4o/config/annotations/.*
- ./org.rssowl.lib.db4o/com/db4o/config/annotations/reflect/.*
- ./org.rssowl.lib.db4o/com/db4o/defragment/.*
- ./org.rssowl.lib.db4o/com/db4o/diagnostic/.*
- ./org.rssowl.lib.db4o/com/db4o/events/.*
- ./org.rssowl.lib.db4o/com/db4o/ext/.*
- ./org.rssowl.lib.db4o/com/db4o/foundation/.*
- ./org.rssowl.lib.db4o/com/db4o/foundation/io/.*
- ./org.rssowl.lib.db4o/com/db4o/foundation/network/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/btree/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/btree/algebra/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/callbacks/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/classindex/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/cluster/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/convert/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/convert/conversions/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/cs/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/cs/messages/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/diagnostic/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/events/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/fieldindex/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/fileheader/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/freespace/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/handlers/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/handlers/net/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/ix/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/mapping/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/marshall/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/query/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/query/processor/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/query/result/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/replication/.*
- ./org.rssowl.lib.db4o/com/db4o/internal/slots/.*
- ./org.rssowl.lib.db4o/com/db4o/io/.*
- ./org.rssowl.lib.db4o/com/db4o/messaging/.*
- ./org.rssowl.lib.db4o/com/db4o/query/.*
- ./org.rssowl.lib.db4o/com/db4o/reflect/.*
- ./org.rssowl.lib.db4o/com/db4o/reflect/core/.*
- ./org.rssowl.lib.db4o/com/db4o/reflect/generic/.*
- ./org.rssowl.lib.db4o/com/db4o/reflect/jdk/.*
- ./org.rssowl.lib.db4o/com/db4o/reflect/self/.*
- ./org.rssowl.lib.db4o/com/db4o/replication/.*
- ./org.rssowl.lib.db4o/com/db4o/types/.*
- ./org.rssowl.lib.httpclient/.*
- ./org.rssowl.lib.httpclient/META-INF/.*
- ./org.rssowl.lib.httpclient/org/.*
- ./org.rssowl.lib.httpclient/org/apache/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/codec/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/codec/binary/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/codec/digest/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/codec/language/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/codec/net/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/auth/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/cookie/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/methods/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/methods/multipart/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/params/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/protocol/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/httpclient/util/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/logging/.*
- ./org.rssowl.lib.httpclient/org/apache/commons/logging/impl/.*
- ./org.rssowl.lib.jdom/.*
- ./org.rssowl.lib.jdom/META-INF/.*
- ./org.rssowl.lib.jdom/org/.*
- ./org.rssowl.lib.jdom/org/jdom/.*
- ./org.rssowl.lib.jdom/org/jdom/adapters/.*
- ./org.rssowl.lib.jdom/org/jdom/filter/.*
- ./org.rssowl.lib.jdom/org/jdom/input/.*
- ./org.rssowl.lib.jdom/org/jdom/output/.*
- ./org.rssowl.lib.jdom/org/jdom/transform/.*
- ./org.rssowl.lib.jdom/org/jdom/xpath/.*
- ./org.rssowl.lib.lucene/.*
- ./org.rssowl.lib.lucene/META-INF/.*
- ./org.rssowl.lib.lucene/org/.*
- ./org.rssowl.lib.lucene/org/apache/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/analysis/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/analysis/standard/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/document/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/index/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/queryParser/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/search/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/search/function/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/search/payloads/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/search/spans/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/store/.*
- ./org.rssowl.lib.lucene/org/apache/lucene/util/.*
- ./org.rssowl.ui/.*
- ./org.rssowl.ui/META-INF/.*
- ./org.rssowl.ui/icons/.*
- ./org.rssowl.ui/icons/dlcl16/.*
- ./org.rssowl.ui/icons/dtool16/.*
- ./org.rssowl.ui/icons/elcl16/.*
- ./org.rssowl.ui/icons/etool16/.*
- ./org.rssowl.ui/icons/eview16/.*
- ./org.rssowl.ui/icons/obj16/.*
- ./org.rssowl.ui/icons/ovr16/.*
- ./org.rssowl.ui/icons/product/.*
- ./org.rssowl.ui/icons/wizban/.*
- ./org.rssowl.ui/schema/.*
